---

- name: Warn if old option 'traefik_network_ipam' is used
  fail:
    msg: "Using 'traefik_network_ipam' is deprecated use traefik_network_ipam_config instead"
  when: 
    - traefik_network_ipam

- name: Warn if old option 'traefik_network_ipam_temp.subnet' is used
  fail:
    msg: "Using 'traefik_network_ipam_temp.subnet' is deprecated use traefik_network_ipam_config instead"
  when: 
    - traefik_network_ipam_temp.subnet

- name: Warn if old option 'traefik_network_ipam_temp.gateway' is used
  fail:
    msg: "Using 'traefik_network_ipam_temp.gateway' is deprecated use traefik_network_ipam_config instead"
  when: 
    - traefik_network_ipam_temp.gateway

- name: Warn if old option 'traefik_network_ipam_temp.iprange' is used
  fail:
    msg: "Using 'traefik_network_ipam_temp.iprange' is deprecated use traefik_network_ipam_config instead"
  when: 
    - traefik_network_ipam_temp.iprange

- name: "config : generate https entrypoint config"
  set_fact:
      traefik_int_conf_entryPoints: "{{
        traefik_int_conf_entryPoints |
        combine(traefik_int_conf_entryPoints_https)
      }}"
  when: traefik_qs_https

- name: "config : generate https redirect config"
  set_fact:
      traefik_int_conf_entryPoints: "{{ traefik_int_conf_entryPoints |
        combine(traefik_int_conf_entryPoints_https_redirect, recursive=True) }}"
  when: traefik_qs_https and traefik_qs_https_redirect


- name: "config : generate neutral certresolver"
  set_fact:
      traefik_conf_certificatesResolvers: "{{
        traefik_int_conf_certificatesResolvers_le
      }}"
  when: traefik_qs_https and traefik_qs_https_le

- name: "config : generate neutral certresolver"
  set_fact:
      traefik_conf_certificatesResolvers: "{{
        traefik_conf_certificatesResolvers | default({})
        | combine(traefik_confkey_certificatesResolvers)
      }}"
  when: traefik_confkey_certificatesResolvers is defined

- name: "config: check if dynamic_configuration has to be disabled"
  set_fact:
      traefik_int_conf_providers_dynamic_configuration: "{{ default({})     
      }}"
  when: traefik_use_dynamic_file_config

- name: "config: generate traefik_conf_providers"
  set_fact:
      traefik_conf_providers: "{{
        traefik_int_conf_providers_docker | combine(traefik_int_conf_providers_dynamic_configuration) | combine(traefik_confkey_providers | default({}))
      }}"

- name: "config : generate static config"
  set_fact:
      traefik_static_config:
          global: "{{ traefik_conf_global }}"
          serversTransport: "{{
            traefik_confkey_serversTransport
            | default(omit)
          }}"
          entryPoints: "{{ traefik_conf_entryPoints }}"
          providers: "{{ traefik_conf_providers }}"
          api: "{{ traefik_confkey_api | default(omit) }}"
          metrics: "{{ traefik_confkey_metrics | default(omit) }}"
          ping: "{{ traefik_confkey_ping | default(omit) }}"
          log: "{{ traefik_conf_log }}"
          accessLog: "{{  traefik_confkey_accessLog | default(omit) }}"
          tracing: "{{ traefik_confkey_tracing | default(omit) }}"
          hostResolver: "{{ traefik_confkey_hostResolver | default(omit) }}"
          certificatesResolvers: "{{
            traefik_conf_certificatesResolvers
            | default(omit)
          }}"
