---

- name: "config : generate https entrypoint config"
  set_fact:
      traefik_int_conf_entryPoints: "{{
        traefik_int_conf_entryPoints |
        combine(traefik_int_conf_entryPoints_https)
      }}"
  when: traefik_qs_https

- name: "config : generate https redirect config"
  set_fact:
      traefik_int_conf_entryPoints: "{{ traefik_int_conf_entryPoints |
        combine(traefik_int_conf_entryPoints_https_redirect, recursive=True) }}"
  when: traefik_qs_https and traefik_qs_https_redirect


- name: "config : generate neutral certresolver"
  set_fact:
      traefik_conf_certificatesResolvers: "{{
        traefik_int_conf_certificatesResolvers_le
      }}"
  when: traefik_qs_https and traefik_qs_https_le

- name: "config : generate neutral certresolver"
  set_fact:
      traefik_conf_certificatesResolvers: "{{
        traefik_conf_certificatesResolvers | default({})
        | combine(traefik_confkey_certificatesResolvers)
      }}"
  when: traefik_confkey_certificatesResolvers is defined

#setup providers
- name: "config: setup docker provider"
  set_fact: 
      traefik_conf_providers: "{{ traefik_int_conf_provider_docker }}"

- name: "config: Setup dynamic file provider"
  set_fact:
      traefik_conf_providers: "{{ traefik_conf_providers | combine(traefik_int_conf_provider_file | default({})) }}"

- name: "config: Setup dynamic file provider using traefik_confkey_providers"
  set_fact:
      traefik_conf_providers: "{{ traefik_conf_providers | combine(traefik_confkey_providers | default({})) }}"
  when: traefik_confkey_providers is defined

# setup basic tls hardening
- name: "config: setup middlewares using traefik_qs_tls_options"
  set_fact: 
      traefik_conf_tls: "{{ traefik_int_conf_tls_options }}"
  when: traefik_qs_tls_options

- name: "config: setup middlewares using traefik_confkey_tls"
  set_fact: 
      traefik_conf_tls: "{{
        traefik_conf_tls | default({})
        | combine(traefik_confkey_tls)
        }}"
  when: traefik_confkey_tls is defined

# setup basic middleware for hardening
- name: "config: setup middlewares using traefik_qs_middlewares"
  set_fact: 
      traefik_conf_middlewares: "{{ traefik_int_conf_http_middlewares }}"
  when: traefik_qs_middlewares

- name: "config: setup middlewares using traefik_confkey_middlewares"
  set_fact: 
      traefik_conf_middlewares: "{{
        traefik_conf_middlewares | default({})
        | combine(traefik_confkey_middlewares)
      }}"
  when: traefik_confkey_middlewares is defined

- name: "config : generate static config"
  set_fact:
      traefik_static_config:
          global: "{{ traefik_conf_global }}"
          serversTransport: "{{
            traefik_confkey_serversTransport
            | default(omit)
          }}"
          entryPoints: "{{ traefik_conf_entryPoints }}"
          providers: "{{ traefik_conf_providers }}"
          api: "{{ traefik_confkey_api | default(omit) }}"
          metrics: "{{ traefik_confkey_metrics | default(omit) }}"
          ping: "{{ traefik_confkey_ping | default(omit) }}"
          log: "{{ traefik_conf_log }}"
          accessLog: "{{  traefik_confkey_accessLog | default(omit) }}"
          tracing: "{{ traefik_confkey_tracing | default(omit) }}"
          hostResolver: "{{ traefik_confkey_hostResolver | default(omit) }}"
          certificatesResolvers: "{{
            traefik_conf_certificatesResolvers
            | default(omit)
          }}"
