---
- name: 'setup : create kibana directory'
  become: true
  file:
    path: '{{ item }}'
    state: directory
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    mode: 0770
  with_items:
    - '{{ kibana_dir }}'

- name: 'setup : create kibana configuration'
  template:
    src: "kibana.yml.j2"
    dest: "{{ kibana_dir }}/kibana.yml"
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    mode: 770
  notify:
    - restart kibana container

- name: 'setup : start kibana container'
  become: true
  docker_container:
    name: '{{ kibana_container_name }}'
    image: '{{ kibana_image }}'
    restart_policy: unless-stopped
    published_ports: '{{ kibana_ports }}'
    volumes: '{{ kibana_volumes + kibana_add_volumes }}'
    labels: '{{ kibana_labels }}'
    env: '{{ kibana_env }}'
    log_options: '{{ kibana_log_options }}'
    networks:
      - name: '{{ kibana_network_name }}'
